tunnel: labmanager-tunnel
credentials-file: /etc/cloudflared/11341f98-e037-4285-920c-be27873d402e.json

ingress:
  - hostname: lab.labdoctors-laboratories.com
    service: http://labmanager-frontend:80

  - hostname: api.labdoctors-laboratories.com
    service: http://labmanager-backend:3001

  - hostname: db.labdoctors-laboratories.com
    service: tcp://labmanager-mysql:3306

  - service: http_status:404
